# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Bun official image as a base
FROM oven/bun:1.0

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and bun.lock for dependency installation
COPY package.json bun.lock ./

# Install the dependencies
RUN bun install

# Copy the entire project
COPY . .

# Build the TypeScript files
RUN bun run build

# Expose the default port if needed (specify the port if the server listens on a specific port)
# EXPOSE 8080

# Set the environment variables (replace placeholders with actual values)
ENV GOOGLE_API_KEY=your_api_key
ENV GOOGLE_SEARCH_ENGINE_ID=your_search_engine_id

# Command to run the server
CMD ["bun", "dist/index.js"]