# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use Bun official image
FROM oven/bun:1.0.0 as builder

# Set working directory
WORKDIR /app

# Copy package and lock files
COPY bun.lock package.json tsconfig.json /app/

# Install dependencies and build the project
RUN bun install && bun run build

# Copy source files and build
COPY src /app/src

# Expose port for the server if needed
EXPOSE 8080

# Run the application
ENTRYPOINT ["bun", "run", "dist/index.js"]
